const jobCategories = [
    {
      name: 'Administrative',
      index: 0,
      subcategories: [
        { name: 'Administrative Assistance', index: 0 },
        { name: 'Executive Assistant', index: 1 },
        { name: 'Office Manager', index: 2 },
        { name: 'Receptionist', index: 3 },
        { name: 'Administrative Assistant', index: 4 },
        { name: 'Data Entry', index: 5 },
        { name: 'Data Entry Clerk', index: 6 },
        { name: 'Database Administrator', index: 7 },
        { name: 'Document Management Specialist', index: 8 },
        { name: 'Recordkeeping Specialist', index: 9 },
        { name: 'Customer Service', index: 10 },
        { name: 'Customer Service Representative', index: 11 },
        { name: 'Call Center Agent', index: 12 },
        { name: 'Help Desk Support Specialist', index: 13 },
        { name: 'Client Services Coordinator', index: 14 },
        { name: 'Client Service Manager', index: 15 },
        { name: 'Office Support', index: 16 },
        { name: 'Office Manager', index: 17 },
        { name: 'Mailroom Clerk', index: 18 },
        { name: 'Facilities Coordinator', index: 19 },
        { name: 'Building Operations Manager', index: 20 },
        { name: 'Office Services Supervisor', index: 21 },
        { name: 'Travel Coordination', index: 22 },
        { name: 'Travel Coordinator', index: 23 },
        { name: 'Travel Agent', index: 24 },
        { name: 'Travel Manager', index: 25 },
        { name: 'Corporate Travel Consultant', index: 26 },
        { name: 'Event Planner', index: 27 },
        { name: 'Project Support', index: 28 },
        { name: 'Project Coordinator', index: 29 },
        { name: 'Project Administrator', index: 30 },
        { name: 'Project Manager Assistant', index: 31 },
        { name: 'Project Scheduler', index: 32 },
        { name: 'Project Expeditor', index: 33 },
        { name: 'Executive Support', index: 34 },
        { name: 'Executive Assistant', index: 35 },
        { name: 'Personal Assistant', index: 36 },
        { name: 'Chief of Staff', index: 37 },
        { name: 'Board Secretary', index: 38 },
        { name: 'Family Office Manager', index: 39 },
        { name: 'Education Support', index: 40 },
        { name: 'Education Administrator', index: 41 },
        { name: 'School Secretary', index: 42 },
        { name: 'Education Program Coordinator', index: 43 },
        { name: 'Admissions Counselor', index: 44 },
        { name: 'Academic Affairs Specialist', index: 45 },
        { name: 'Records Management', index: 46 },
        { name: 'Records Manager', index: 47 },
        { name: 'Document Control Specialist', index: 48 },
        { name: 'Archivist', index: 49 },
        { name: 'Information Governance Specialist', index: 50 },
        { name: 'Records Analyst', index: 51 },
      ]
    },
    {
      name: 'Agriculture and Natural Resources',
      index: 1,
      subcategories: [
        { name: 'Agronomy', index: 0 },
        { name: 'Agronomist', index: 1 },
        { name: 'Crop Consultant', index: 2 },
        { name: 'Soil Scientist', index: 3 },
        { name: 'Agricultural Engineering', index: 4 },
        { name: 'Agricultural Engineer', index: 5 },
        { name: 'Irrigation Engineer', index: 6 },
        { name: 'Farm Equipment Designer', index: 7 },
        { name: 'Horticulture', index: 8 },
        { name: 'Horticulturist', index: 9 },
        { name: 'Landscape Architect', index: 10 },
        { name: 'Arborist', index: 11 },
        { name: 'Animal Science', index: 12 },
        { name: 'Animal Scientist', index: 13 },
        { name: 'Livestock Manager', index: 14 },
        { name: 'Veterinary Technician', index: 15 },
        { name: 'Agribusiness and Farm Management', index: 16 },
        { name: 'Farm Manager', index: 17 },
        { name: 'Ranch Manager', index: 18 },
        { name: 'Agricultural Business Specialist', index: 19 },
        { name: 'Environmental Science and Management', index: 20 },
        { name: 'Environmental Scientist', index: 21 },
        { name: 'Natural Resource Manager', index: 22 },
        { name: 'Sustainability Analyst', index: 23 },
        { name: 'Fisheries and Wildlife', index: 24 },
        { name: 'Fisheries Biologist', index: 25 },
        { name: 'Wildlife Biologist', index: 26 },
        { name: 'Fish and Wildlife Manager', index: 27 },
        { name: 'Forestry and Forest Management', index: 28 },
        { name: 'Forester', index: 29 },
        { name: 'Forest Manager', index: 30 },
        { name: 'Timber Harvesting Technician', index: 31 },
        { name: 'Natural Resources Management and Policy', index: 32 },
        { name: 'Natural Resource Policy Analyst', index: 33 },
        { name: 'Land Use Planner', index: 34 },
        { name: 'Wildlife Management Specialist', index: 35 },
        { name: 'Plant Science', index: 36 },
        { name: 'Plant Scientist', index: 37 },
        { name: 'Plant Breeder', index: 38 },
        { name: 'Plant Pathologist', index: 39 },
        { name: 'Range Management', index: 40 },
        { name: 'Range Manager', index: 41 },
        { name: 'Grazing Specialist', index: 42 },
        { name: 'Rangeland Ecologist', index: 43 },
        { name: 'Soil Science', index: 44 },
        { name: 'Soil Scientist', index: 45 },
        { name: 'Soil Conservationist', index: 46 },
        { name: 'Land Reclamation Specialist', index: 47 },
        { name: 'Food Science and Technology', index: 48 },
        { name: 'Food Scientist', index: 49 },
        { name: 'Food Technologist', index: 50 },
        { name: 'Quality Control Manager', index: 51 },
      ]
    },
    {
      name: 'Construction and Trades',
      index: 2,
      subcategories: [
        { name: 'Carpentry and Woodworking', index: 0 },
        { name: 'Carpenter', index: 1 },
        { name: 'Cabinet Maker', index: 2 },
        { name: 'Woodworker', index: 3 },
        { name: 'Furniture Maker', index: 4 },
        { name: 'Joiner', index: 5 },
        { name: 'Masonry and Bricklaying', index: 6 },
        { name: 'Mason', index: 7 },
        { name: 'Bricklayer', index: 8 },
        { name: 'Stone Mason', index: 9 },
        { name: 'Restoration Specialist', index: 10 },
        { name: 'Tile Setter', index: 11 },
        { name: 'Plumbing and Pipefitting', index: 12 },
        { name: 'Plumber', index: 13 },
        { name: 'Pipefitter', index: 14 },
        { name: 'Gasfitter', index: 15 },
        { name: 'Steamfitter', index: 16 },
        { name: 'Sprinkler Fitter', index: 17 },
        { name: 'Electrical', index: 18 },
        { name: 'Electrician', index: 19 },
        { name: 'Electrical Engineer', index: 20 },
        { name: 'Electrical Estimator', index: 21 },
        { name: 'Electrical Designer', index: 22 },
        { name: 'Electrical Project Manager', index: 23 },
        { name: 'HVAC and Refrigeration', index: 24 },
        { name: 'HVAC Technician', index: 25 },
        { name: 'HVAC Sales Representative', index: 26 },
        { name: 'HVAC Service Manager', index: 27 },
        { name: 'Refrigeration Technician', index: 28 },
        { name: 'HVAC Engineer', index: 29 },
        { name: 'Roofing and Siding', index: 30 },
        { name: 'Roofer', index: 31 },
        { name: 'Siding Installer', index: 32 },
        { name: 'Sheet Metal Worker', index: 33 },
        { name: 'Metal Roofer', index: 34 },
        { name: 'Flat Roofer', index: 35 },
        { name: 'Painting and Decorating', index: 36 },
        { name: 'Painter', index: 37 },
        { name: 'Decorator', index: 38 },
        { name: 'Wallpaper Hanger', index: 39 },
        { name: 'Faux Finisher', index: 40 },
        { name: 'Industrial Painter', index: 41 },
        { name: 'Flooring and Tiling', index: 42 },
        { name: 'Flooring Installer', index: 43 },
        { name: 'Tile Setter', index: 44 },
        { name: 'Carpet Installer', index: 45 },
        { name: 'Flooring Estimator', index: 46 },
        { name: 'Tile Sales Representative', index: 47 },
        { name: 'Concrete and Cement Work', index: 48 },
        { name: 'Concrete Finisher', index: 49 },
        { name: 'Cement Mason', index: 50 },
        { name: 'Concrete Pump Operator', index: 51 },
        { name: 'Concrete Estimator', index: 52 },
        { name: 'Concrete Mixer Driver', index: 53 },
        { name: 'Welding and Metalworking', index: 54 },
        { name: 'Welder', index: 55 },
        { name: 'Fabricator', index: 56 },
        { name: 'Metalworker', index: 57 },
        { name: 'Blacksmith', index: 58 },
        { name: 'Metal Artist', index: 59 },
        { name: 'Heavy Equipment Operation', index: 60 },
        { name: 'Heavy Equipment Operator', index: 61 },
        { name: 'Excavator Operator', index: 62 },
        { name: 'Bulldozer Operator', index: 63 },
        { name: 'Crane Operator', index: 64 },
        { name: 'Pile Driver Operator', index: 65 },
        { name: 'Landscaping and Horticulture', index: 66 },
        { name: 'Landscape Architect', index: 67 },
        { name: 'Landscape Designer', index: 68 },
        { name: 'Landscape Installer', index: 69 },
        { name: 'Irrigation Technician', index: 70 },
        { name: 'Horticulturist', index: 71 },
        { name: 'Carpentry Finishing and Cabinetry', index: 72 },
        { name: 'Finish Carpenter', index: 73 },
        { name: 'Cabinet Installer', index: 74 },
        { name: 'Furniture Finisher', index: 75 },
        { name: 'Stair Builder', index: 76 },
        { name: 'Trim Carpenter', index: 77 },
        { name: 'Drywall and Insulation', index: 78 },
        { name: 'Drywaller', index: 79 },
        { name: 'Insulation Installer', index: 80 },
        { name: 'Acoustical Ceiling Installer', index: 81 },
        { name: 'Drywall Finisher', index: 82 },
        { name: 'Insulation Estimator', index: 83 },
        { name: 'Glazing and Glasswork', index: 84 },
        { name: 'Glazier', index: 85 },
        { name: 'Glass Installer', index: 86 },
        { name: 'Glass Fabricator', index: 87 },
        { name: 'Glass Estimator', index: 88 },
        { name: 'Glass Project Manager', index: 89 },
        { name: 'Demolition and Wrecking', index: 90 },
        { name: 'Demolition Manager', index: 91 },
        { name: 'Demolition Equipment Operator', index: 92 },
        { name: 'Demolition Laborer', index: 93 },
        { name: 'Demolition Estimator', index: 94 },
        { name: 'Wrecking Ball Operator', index: 95 },
        { name: 'Restoration and Preservation', index: 96 },
        { name: 'Historic Preservation Specialist', index: 97 },
        { name: 'Restoration Contractor', index: 98 },
        { name: 'Disaster Recovery Specialist', index: 99 },
        { name: 'Masonry Restoration Specialist', index: 100 },
        { name: 'Building Restoration Estimator', index: 101 },
        { name: 'Environmental and Green Construction', index: 102 },
        { name: 'Sustainable Construction Manager', index: 103 },
        { name: 'LEED Accredited Professional', index: 104 },
        { name: 'Energy Auditor', index: 105 },
        { name: 'Green Building Consultant', index: 106 },
        { name: 'Building Energy Specialist', index: 107 },
        { name: 'Project Management', index: 108 },
        { name: 'Construction Manager', index: 109 },
        { name: 'Project Manager', index: 110 },
        { name: 'Estimator', index: 111 },
        { name: 'Construction Scheduler', index: 112 },
        { name: 'Quality Control Manager', index: 113 },
        { name: 'Safety and Health', index: 114 },
        { name: 'Safety Manager', index: 115 },
        { name: 'Health and Safety Coordinator', index: 116 },
        { name: 'Safety Trainer', index: 117 },
        { name: 'Safety Inspector', index: 118 },
        { name: 'Occupational Health Specialist', index: 119 },
      ]
    },
    {
      name: 'Corporate Affairs',
      index: 3,
      subcategories: [
        { name: 'Public Relations (PR)', index: 0 },
        { name: 'PR Specialist', index: 1 },
        { name: 'PR Manager', index: 2 },
        { name: 'PR Director', index: 3 },
        { name: 'Investor Relations (IR)', index: 4 },
        { name: 'Investor Relations Manager', index: 5 },
        { name: 'Investor Relations Director', index: 6 },
        { name: 'Investor Relations Analyst', index: 7 },
        { name: 'Communications', index: 8 },
        { name: 'Communications Specialist', index: 9 },
        { name: 'Communications Manager', index: 10 },
        { name: 'Communications Director', index: 11 },
        { name: 'Corporate Social Responsibility (CSR)', index: 12 },
        { name: 'CSR Specialist', index: 13 },
        { name: 'CSR Manager', index: 14 },
        { name: 'CSR Director', index: 15 },
        { name: 'Government Relations', index: 16 },
        { name: 'Government Relations Specialist', index: 17 },
        { name: 'Government Relations Manager', index: 18 },
        { name: 'Government Relations Director', index: 19 },
        { name: 'Public Affairs', index: 20 },
        { name: 'Public Affairs Specialist', index: 21 },
        { name: 'Public Affairs Manager', index: 22 },
        { name: 'Public Affairs Director', index: 23 },
        { name: 'Community Relations', index: 24 },
        { name: 'Community Relations Manager', index: 25 },
        { name: 'Community Relations Specialist', index: 26 },
        { name: 'Community Relations Director', index: 27 },
        { name: 'Corporate Reputation Management', index: 28 },
        { name: 'Reputation Management Specialist', index: 29 },
        { name: 'Reputation Management Manager', index: 30 },
        { name: 'Reputation Management Director', index: 31 },
        { name: 'Stakeholder Engagement', index: 32 },
        { name: 'Stakeholder Engagement Manager', index: 33 },
        { name: 'Stakeholder Engagement Specialist', index: 34 },
        { name: 'Stakeholder Engagement Director', index: 35 },
        { name: 'Brand Management', index: 36 },
        { name: 'Brand Manager', index: 37 },
        { name: 'Brand Specialist', index: 38 },
        { name: 'Brand Director', index: 39 },
        { name: 'Marketing Communications', index: 40 },
        { name: 'Marketing Communications Manager', index: 41 },
        { name: 'Marketing Communications Specialist', index: 42 },
        { name: 'Marketing Communications Director', index: 43 },
        { name: 'Crisis Communications', index: 44 },
        { name: 'Crisis Communications Manager', index: 45 },
        { name: 'Crisis Communications Specialist', index: 46 },
        { name: 'Crisis Communications Director', index: 47 },
        { name: 'Internal Communications', index: 48 },
        { name: 'Internal Communications Specialist', index: 49 },
        { name: 'Internal Communications Manager', index: 50 },
        { name: 'Internal Communications Director', index: 51 },
        { name: 'Media Relations', index: 52 },
        { name: 'Media Relations Specialist', index: 53 },
        { name: 'Media Relations Manager', index: 54 },
        { name: 'Media Relations Director', index: 55 },
        { name: 'Corporate Philanthropy', index: 56 },
        { name: 'Philanthropy Manager', index: 57 },
        { name: 'Philanthropy Specialist', index: 58 },
        { name: 'Philanthropy Director', index: 59 },
        { name: 'Issues Management', index: 60 },
        { name: 'Issues Management Specialist', index: 61 },
        { name: 'Issues Management Manager', index: 62 },
        { name: 'Issues Management Director', index: 63 },
        { name: 'Reputation Risk Management', index: 64 },
        { name: 'Reputation Risk Manager', index: 65 },
        { name: 'Reputation Risk Specialist', index: 66 },
        { name: 'Reputation Risk Director', index: 67 },
        { name: 'Corporate Diplomacy', index: 68 },
        { name: 'Corporate Diplomacy Manager', index: 69 },
        { name: 'Corporate Diplomacy Specialist', index: 70 },
        { name: 'Corporate Diplomacy Director', index: 71 },
        { name: 'Strategic Communications', index: 72 },
        { name: 'Strategic Communications Manager', index: 73 },
        { name: 'Strategic Communications Specialist', index: 74 },
        { name: 'Strategic Communications Director', index: 75 },
      ]
    },
    {
      name: 'Creative and Media',
      index: 4,
      subcategories: [
        { name: 'Advertising', index: 0 },
        { name: 'Account Executive', index: 1 },
        { name: 'Advertising Copywriter', index: 2 },
        { name: 'Art Director', index: 3 },
        { name: 'Media Planner', index: 4 },
        { name: 'Ad Sales Representative', index: 5 },
        { name: 'Film and Video Production', index: 6 },
        { name: 'Producer', index: 7 },
        { name: 'Director', index: 8 },
        { name: 'Screenwriter', index: 9 },
        { name: 'Editor', index: 10 },
        { name: 'Cinematographer', index: 11 },
        { name: 'Graphic Design', index: 12 },
        { name: 'Graphic Designer', index: 13 },
        { name: 'Creative Director', index: 14 },
        { name: 'Web Designer', index: 15 },
        { name: 'Visual Designer', index: 16 },
        { name: 'Brand Identity Designer', index: 17 },
        { name: 'Journalism', index: 18 },
        { name: 'Journalist', index: 19 },
        { name: 'News Anchor', index: 20 },
        { name: 'Editor', index: 21 },
        { name: 'Copy Editor', index: 22 },
        { name: 'Photojournalist', index: 23 },
        { name: 'Music', index: 24 },
        { name: 'Musician', index: 25 },
        { name: 'Composer', index: 26 },
        { name: 'Music Producer', index: 27 },
        { name: 'Sound Engineer', index: 28 },
        { name: 'Music Therapist', index: 29 },
        { name: 'Photography', index: 30 },
        { name: 'Photographer', index: 31 },
        { name: 'Photo Editor', index: 32 },
        { name: 'Photojournalist', index: 33 },
        { name: 'Product Photographer', index: 34 },
        { name: 'Wedding Photographer', index: 35 },
        { name: 'Public Relations', index: 36 },
        { name: 'Public Relations Specialist', index: 37 },
        { name: 'Communications Director', index: 38 },
        { name: 'Social Media Manager', index: 39 },
        { name: 'Corporate Communications Manager', index: 40 },
        { name: 'Crisis Communications Specialist', index: 41 },
        { name: 'Radio', index: 42 },
        { name: 'Radio DJ', index: 43 },
        { name: 'Radio Producer', index: 44 },
        { name: 'Radio Announcer', index: 45 },
        { name: 'Radio Advertising Sales Representative', index: 46 },
        { name: 'Radio Program Director', index: 47 },
        { name: 'Television', index: 48 },
        { name: 'Television Producer', index: 49 },
        { name: 'Television Writer', index: 50 },
        { name: 'News Anchor', index: 51 },
        { name: 'TV Advertising', index: 52 },
        { name: 'Visual Arts', index: 53 },
        { name: 'Fine Artist', index: 54 },
        { name: 'Illustrator', index: 55 },
        { name: 'Muralist', index: 56 },
        { name: 'Sculptor', index: 57 },
        { name: 'Gallery Manager', index: 58 },
        { name: 'Publishing', index: 59 },
        { name: 'Publisher', index: 60 },
        { name: 'Editor', index: 61 },
        { name: 'Literary Agent', index: 62 },
        { name: 'Proofreader', index: 63 },
        { name: 'Book Designer', index: 64 },
        { name: 'Animation', index: 65 },
        { name: 'Animator', index: 66 },
        { name: '3D Modeler', index: 67 },
        { name: 'Motion Graphics Designer', index: 68 },
        { name: 'Storyboard Artist', index: 69 },
        { name: 'Character Designer', index: 70 },
        { name: 'Copywriting', index: 71 },
        { name: 'Copywriter', index: 72 },
        { name: 'Content Marketing Specialist', index: 73 },
        { name: 'Advertising Copywriter', index: 74 },
        { name: 'Technical Writer', index: 75 },
        { name: 'Email Marketing Manager', index: 76 },
        { name: 'Multimedia', index: 77 },
        { name: 'Multimedia Designer', index: 78 },
        { name: 'Interactive Designer', index: 79 },
        { name: 'Virtual Reality Designer', index: 80 },
        { name: 'Augmented Reality Developer', index: 81 },
        { name: 'E-learning Developer', index: 82 },
        { name: 'Game Design', index: 83 },
        { name: 'Game Designer', index: 84 },
        { name: 'Game Programmer', index: 85 },
        { name: 'Game Artist', index: 86 },
        { name: 'Game Tester', index: 87 },
        { name: 'Game Writer', index: 88 },
        { name: 'Theater', index: 89 },
        { name: 'Actor', index: 90 },
        { name: 'Theater Director', index: 91 },
        { name: 'Playwright', index: 92 },
        { name: 'Stage Manager', index: 93 },
        { name: 'Set Designer', index: 94 },
        { name: 'Fashion Design', index: 95 },
        { name: 'Fashion Designer', index: 96 },
        { name: 'Fashion Illustrator', index: 97 },
        { name: 'Textile Designer', index: 98 },
        { name: 'Fashion Buyer', index: 99 },
        { name: 'Fashion Merchandiser', index: 100 },
        { name: 'Dance', index: 101 },
        { name: 'Dancer', index: 102 },
        { name: 'Choreographer', index: 103 },
        { name: 'Dance Instructor', index: 104 },
        { name: 'Dance Therapist', index: 105 },
        { name: 'Dance Company Manager', index: 106 },
        { name: 'Creative Writing', index: 107 },
        { name: 'Writer', index: 108 },
        { name: 'Novelist', index: 109 },
        { name: 'Poet', index: 110 },
        { name: 'Screenwriter', index: 111 },
        { name: 'Playwright', index: 112 },
      ]
    },
    {
      name: 'Education and Training',
      index: 5,
      subcategories: [
        { name: 'Early Childhood Education', index: 0 },
        { name: 'Preschool Teacher', index: 1 },
        { name: 'Kindergarten Teacher', index: 2 },
        { name: 'Daycare Provider', index: 3 },
        { name: 'Childcare Center Director', index: 4 },
        { name: 'Early Childhood Education Specialist', index: 5 },
        { name: 'Elementary Education', index: 6 },
        { name: 'Elementary School Teacher', index: 7 },
        { name: 'Resource Teacher', index: 8 },
        { name: 'Special Education Teacher', index: 9 },
        { name: 'Curriculum Specialist', index: 10 },
        { name: 'Reading Specialist', index: 11 },
        { name: 'Secondary Education', index: 12 },
        { name: 'High School Teacher', index: 13 },
        { name: 'Middle School Teacher', index: 14 },
        { name: 'Subject Matter Specialist', index: 15 },
        { name: 'Counselor', index: 16 },
        { name: 'Coach', index: 17 },
        { name: 'Special Education', index: 18 },
        { name: 'Special Education Teacher', index: 19 },
        { name: 'Behavior Interventionist', index: 20 },
        { name: 'Speech-Language Pathologist', index: 21 },
        { name: 'Occupational Therapist', index: 22 },
        { name: 'Education Diagnostician', index: 23 },
        { name: 'Education Administration', index: 24 },
        { name: 'School Principal', index: 25 },
        { name: 'School Superintendent', index: 26 },
        { name: 'Curriculum Director', index: 27 },
        { name: 'Education Consultant', index: 28 },
        { name: 'Education Policy Analyst', index: 29 },
        { name: 'Curriculum and Instruction', index: 30 },
        { name: 'Curriculum Specialist', index: 31 },
        { name: 'Instructional Designer', index: 32 },
        { name: 'Learning and Development Manager', index: 33 },
        { name: 'Instructional Coach', index: 34 },
        { name: 'E-Learning Specialist', index: 35 },
        { name: 'Adult Education', index: 36 },
        { name: 'Adult Education Teacher', index: 37 },
        { name: 'GED Instructor', index: 38 },
        { name: 'English as a Second Language (ESL) Teacher', index: 39 },
        { name: 'Literacy Tutor', index: 40 },
        { name: 'Vocational Education Instructor', index: 41 },
        { name: 'Educational Technology', index: 42 },
        { name: 'Educational Technology Specialist', index: 43 },
        { name: 'Technology Integration Specialist', index: 44 },
        { name: 'E-Learning Designer', index: 45 },
        { name: 'Instructional Technologist', index: 46 },
        { name: 'Learning Management System (LMS) Administrator', index: 47 },
        { name: 'Higher Education', index: 48 },
        { name: 'College Professor', index: 49 },
        { name: 'Admissions Counselor', index: 50 },
        { name: 'Financial Aid Advisor', index: 51 },
        { name: 'Academic Advisor', index: 52 },
        { name: 'Registrar', index: 53 },
        { name: 'Library Science', index: 54 },
        { name: 'Librarian', index: 55 },
        { name: 'Library Assistant', index: 56 },
        { name: 'Archivist', index: 57 },
        { name: 'Digital Archivist', index: 58 },
        { name: 'Library Director', index: 59 },
        { name: 'Museum Education', index: 60 },
        { name: 'Museum Educator', index: 61 },
        { name: 'Exhibit Designer', index: 62 },
        { name: 'Docent', index: 63 },
        { name: 'Curator', index: 64 },
        { name: 'Education Program Manager', index: 65 },
        { name: 'Education Research', index: 66 },
        { name: 'Education Researcher', index: 67 },
        { name: 'Program Evaluator', index: 68 },
        { name: 'Data Analyst', index: 69 },
        { name: 'Survey Researcher', index: 70 },
        { name: 'Quantitative Researcher', index: 71 },
        { name: 'School Counseling', index: 72 },
        { name: 'School Counselor', index: 73 },
        { name: 'School Psychologist', index: 74 },
        { name: 'School Social Worker', index: 75 },
        { name: 'Behavior Specialist', index: 76 },
        { name: 'Family Engagement Coordinator', index: 77 },
        { name: 'Educational Leadership', index: 78 },
        { name: 'Educational Leader', index: 79 },
        { name: 'Educational Coach', index: 80 },
        { name: 'Instructional Coordinator', index: 81 },
        { name: 'Education Consultant', index: 82 },
        { name: 'Education Policy Analyst', index: 83 },
        { name: 'Outdoor Education', index: 84 },
        { name: 'Outdoor Education Teacher', index: 85 },
        { name: 'Environmental Education Specialist', index: 86 },
        { name: 'Adventure Education Instructor', index: 87 },
        { name: 'Outdoor Education Program Coordinator', index: 88 },
        { name: 'Outdoor Education Camp Director', index: 89 },
        { name: 'Physical Education', index: 90 },
        { name: 'Physical Education Teacher', index: 91 },
        { name: 'Athletic Coach', index: 92 },
        { name: 'Fitness Instructor', index: 93 },
        { name: 'Physical Education Program Coordinator', index: 94 },
        { name: 'Sports Administrator', index: 95 },
        { name: 'International Education', index: 96 },
        { name: 'International Education Coordinator', index: 97 },
        { name: 'Study Abroad Advisor', index: 98 },
        { name: 'Foreign Language Teacher', index: 99 },
        { name: 'International Admissions Officer', index: 100 },
        { name: 'International Program Manager', index: 101 },
        { name: 'Multicultural Education', index: 102 },
        { name: 'Diversity Specialist', index: 103 },
        { name: 'Multicultural Education Coordinator', index: 104 },
        { name: 'Bilingual Teacher', index: 105 },
        { name: 'Cultural Competency Trainer', index: 106 },
        { name: 'Multicultural Education Consultant', index: 107 },
        { name: 'Educational Assessment', index: 108 },
        { name: 'Assessment Specialist', index: 109 },
        { name: 'Testing Coordinator', index: 110 },
        { name: 'Evaluation Analyst', index: 111 },
        { name: 'Assessment Developer', index: 112 },
        { name: 'Career and Technical Education', index: 113 },
        { name: 'Career and Technical Education Teacher', index: 114 },
        { name: 'Workforce Development Coordinator', index: 115 },
        { name: 'Apprenticeship Trainer', index: 116 },
        { name: 'Vocational Education Instructor', index: 117 },
        { name: 'Career Counselor', index: 118 },
      ]
    },
    {
      name: 'Engineering',
      index: 6,
      subcategories: [
        { name: 'Civil Engineering', index: 0 },
        { name: 'Structural Engineer', index: 1 },
        { name: 'Geotechnical Engineer', index: 2 },
        { name: 'Transportation Engineer', index: 3 },
        { name: 'Water Resources Engineer', index: 4 },
        { name: 'Environmental Engineer', index: 5 },
        { name: 'Mechanical Engineering', index: 6 },
        { name: 'Mechanical Design Engineer', index: 7 },
        { name: 'Manufacturing Engineer', index: 8 },
        { name: 'Robotics Engineer', index: 9 },
        { name: 'HVAC Engineer', index: 10 },
        { name: 'Aerospace Engineer', index: 11 },
        { name: 'Electrical Engineering', index: 12 },
        { name: 'Electrical Design Engineer', index: 13 },
        { name: 'Power Systems Engineer', index: 14 },
        { name: 'Control Systems Engineer', index: 15 },
        { name: 'Electronics Engineer', index: 16 },
        { name: 'Telecommunications Engineer', index: 17 },
        { name: 'Chemical Engineering', index: 18 },
        { name: 'Process Engineer', index: 19 },
        { name: 'Materials Engineer', index: 20 },
        { name: 'Petrochemical Engineer', index: 21 },
        { name: 'Biomedical Engineer', index: 22 },
        { name: 'Environmental Engineer', index: 23 },
        { name: 'Industrial Engineering', index: 24 },
        { name: 'Industrial Designer', index: 25 },
        { name: 'Quality Control Engineer', index: 26 },
        { name: 'Manufacturing Engineer', index: 27 },
        { name: 'Operations Manager', index: 28 },
        { name: 'Logistics Engineer', index: 29 },
        { name: 'Aerospace Engineering', index: 30 },
        { name: 'Aerospace Design Engineer', index: 31 },
        { name: 'Aerodynamics Engineer', index: 32 },
        { name: 'Avionics Engineer', index: 33 },
        { name: 'Flight Test Engineer', index: 34 },
        { name: 'Propulsion Engineer', index: 35 },
        { name: 'Computer Engineering', index: 36 },
        { name: 'Computer Hardware Engineer', index: 37 },
        { name: 'Computer Network Architect', index: 38 },
        { name: 'Robotics Engineer', index: 39 },
        { name: 'Embedded Systems Engineer', index: 40 },
        { name: 'Cybersecurity Engineer', index: 41 },
        { name: 'Environmental Engineering', index: 42 },
        { name: 'Environmental Scientist', index: 43 },
        { name: 'Air Quality Engineer', index: 44 },
        { name: 'Water Treatment Engineer', index: 45 },
        { name: 'Waste Management Engineer', index: 46 },
        { name: 'Sustainability Engineer', index: 47 },
        { name: 'Software Engineering', index: 48 },
        { name: 'Software Developer', index: 49 },
        { name: 'Software Architect', index: 50 },
        { name: 'Database Engineer', index: 51 },
        { name: 'Data Scientist', index: 52 },
        { name: 'DevOps Engineer', index: 53 },
        { name: 'Mechatronics Engineering', index: 54 },
        { name: 'Mechatronics Engineer', index: 55 },
        { name: 'Robotics Engineer', index: 56 },
        { name: 'Control Systems Engineer', index: 57 },
        { name: 'Automation Engineer', index: 58 },
        { name: 'Embedded Systems Engineer', index: 59 },
        { name: 'Acoustical Engineering', index: 60 },
        { name: 'Acoustical Engineer', index: 61 },
        { name: 'Audio Engineer', index: 62 },
        { name: 'Noise Control Engineer', index: 63 },
        { name: 'Vibration Engineer', index: 64 },
        { name: 'Room Acoustics Engineer', index: 65 },
        { name: 'Environmental Engineering', index: 66 },
        { name: 'Air Quality Engineer', index: 67 },
        { name: 'Water Quality Engineer', index: 68 },
        { name: 'Solid Waste Engineer', index: 69 },
        { name: 'Environmental Scientist', index: 70 },
        { name: 'Environmental Consultant', index: 71 },
        { name: 'Structural Engineering', index: 72 },
        { name: 'Bridge Engineer', index: 73 },
        { name: 'Building Engineer', index: 74 },
        { name: 'Seismic Engineer', index: 75 },
        { name: 'Wind Engineer', index: 76 },
        { name: 'Construction Engineer', index: 77 },
        { name: 'Geological Engineering', index: 78 },
        { name: 'Geologist', index: 79 },
        { name: 'Geotechnical Engineer', index: 80 },
        { name: 'Mining Engineer', index: 81 },
        { name: 'Hydrogeologist', index: 82 },
        { name: 'Environmental Engineer', index: 83 },
        { name: 'Optical Engineering', index: 84 },
        { name: 'Optical Design Engineer', index: 85 },
        { name: 'Laser Engineer', index: 86 },
        { name: 'Optical Systems Engineer', index: 87 },
        { name: 'Opto-Mechanical Engineer', index: 88 },
        { name: 'Image Processing Engineer', index: 89 },
        { name: 'Agricultural Engineering', index: 90 },
        { name: 'Agricultural Engineer', index: 91 },
        { name: 'Irrigation Engineer', index: 92 },
        { name: 'Farm Equipment Engineer', index: 93 },
        { name: 'Food Processing Engineer', index: 94 },
        { name: 'Bioenergy Engineer', index: 95 },
        { name: 'Materials Engineering', index: 96 },
        { name: 'Metallurgical Engineer', index: 97 },
        { name: 'Ceramic Engineer', index: 98 },
        { name: 'Polymer Engineer', index: 99 },
        { name: 'Nanotechnology Engineer', index: 100 },
        { name: 'Corrosion Engineer', index: 101 },
        { name: 'Biomedical Engineering', index: 102 },
        { name: 'Biomechanical Engineer', index: 103 },
        { name: 'Biomaterials Engineer', index: 104 },
        { name: 'Medical Device Engineer', index: 105 },
        { name: 'Imaging Engineer', index: 106 },
        { name: 'Tissue Engineer', index: 107 },
        { name: 'Petroleum Engineering', index: 108 },
        { name: 'Drilling Engineer', index: 109 },
        { name: 'Reservoir Engineer', index: 110 },
        { name: 'Production Engineer', index: 111 },
        { name: 'Completions Engineer', index: 112 },
        { name: 'Operations Engineer', index: 113 },
        { name: 'Mining Engineering', index: 114 },
        { name: 'Mine Engineer', index: 115 },
        { name: 'Mineral Processing Engineer', index: 116 },
        { name: 'Rock Mechanics Engineer', index: 117 },
        { name: 'Mining Safety Engineer', index: 118 },
        { name: 'Environmental Engineer', index: 119 },
        { name: 'Nuclear Engineering', index: 120 },
        { name: 'Reactor Engineer', index: 121 },
        { name: 'Radiation Protection Engineer', index: 122 },
        { name: 'Nuclear Safety Engineer', index: 123 },
        { name: 'Nuclear Fuel Engineer', index: 124 },
        { name: 'Waste Management Engineer', index: 125 },
        { name: 'Marine Engineering', index: 126 },
        { name: 'Naval Architect', index: 127 },
        { name: 'Marine Engineer', index: 128 },
        { name: 'Marine Surveyor', index: 129 },
        { name: 'Marine Electrical Engineer', index: 130 },
        { name: 'Marine Mechanical Engineer', index: 131 },
        { name: 'Systems Engineering', index: 132 },
        { name: 'Systems Engineer', index: 133 },
        { name: 'Systems Integration Engineer', index: 134 },
        { name: 'Requirements Engineer', index: 135 },
        { name: 'Test Engineer', index: 136 },
        { name: 'Project Engineer', index: 137 },
        { name: 'Robotics Engineering', index: 138 },
        { name: 'Robotics Engineer', index: 139 },
        { name: 'Controls Engineer', index: 140 },
        { name: 'AI Engineer', index: 141 },
        { name: 'Perception Engineer', index: 142 },
        { name: 'Motion Planning Engineer', index: 143 },
      ]
    },
    {
      name: 'Finance & Accounting',
      index: 7,
      subcategories: [
        { name: 'Accounting', index: 0 },
        { name: 'Accountant', index: 1 },
        { name: 'Auditor', index: 2 },
        { name: 'Bookkeeper', index: 3 },
        { name: 'Tax Accountant', index: 4 },
        { name: 'Forensic Accountant', index: 5 },
        { name: 'Financial Analysis', index: 6 },
        { name: 'Financial Analyst', index: 7 },
        { name: 'Investment Analyst', index: 8 },
        { name: 'Business Analyst', index: 9 },
        { name: 'Credit Analyst', index: 10 },
        { name: 'Risk Analyst', index: 11 },
        { name: 'Corporate Finance', index: 12 },
        { name: 'Chief Financial Officer (CFO)', index: 13 },
        { name: 'Financial Manager', index: 14 },
        { name: 'Treasury Analyst', index: 15 },
        { name: 'Mergers and Acquisitions Specialist', index: 16 },
        { name: 'Financial Controller', index: 17 },
        { name: 'Banking', index: 18 },
        { name: 'Bank Teller', index: 19 },
        { name: 'Loan Officer', index: 20 },
        { name: 'Branch Manager', index: 21 },
        { name: 'Investment Banker', index: 22 },
        { name: 'Credit Manager', index: 23 },
        { name: 'Investment Management', index: 24 },
        { name: 'Investment Manager', index: 25 },
        { name: 'Portfolio Manager', index: 26 },
        { name: 'Hedge Fund Manager', index: 27 },
        { name: 'Private Equity Manager', index: 28 },
        { name: 'Wealth Manager', index: 29 },
        { name: 'Financial Planning', index: 30 },
        { name: 'Financial Planner', index: 31 },
        { name: 'Retirement Planner', index: 32 },
        { name: 'Estate Planner', index: 33 },
        { name: 'Wealth Advisor', index: 34 },
        { name: 'Certified Financial Planner (CFP)', index: 35 },
        { name: 'Insurance', index: 36 },
        { name: 'Insurance Agent', index: 37 },
        { name: 'Claims Adjuster', index: 38 },
        { name: 'Underwriter', index: 39 },
        { name: 'Risk Manager', index: 40 },
        { name: 'Actuary', index: 41 },
        { name: 'Financial Services', index: 42 },
        { name: 'Financial Advisor', index: 43 },
        { name: 'Personal Banker', index: 44 },
        { name: 'Wealth Management Advisor', index: 45 },
        { name: 'Financial Consultant', index: 46 },
        { name: 'Retirement Plan Consultant', index: 47 },
        { name: 'Taxation', index: 48 },
        { name: 'Tax Specialist', index: 49 },
        { name: 'Tax Consultant', index: 50 },
        { name: 'Tax Advisor', index: 51 },
        { name: 'Tax Accountant', index: 52 },
        { name: 'IRS Agent', index: 53 },
        { name: 'Financial Regulation', index: 54 },
        { name: 'Compliance Officer', index: 55 },
        { name: 'Financial Analyst', index: 56 },
        { name: 'Securities Lawyer', index: 57 },
        { name: 'Banking Supervisor', index: 58 },
        { name: 'Treasury Management', index: 59 },
        { name: 'Treasury Manager', index: 60 },
        { name: 'Cash Manager', index: 61 },
        { name: 'Liquidity Manager', index: 62 },
        { name: 'Financial Strategist', index: 63 },
        { name: 'Financial Operations', index: 64 },
        { name: 'Operations Manager', index: 65 },
        { name: 'Financial Operations Analyst', index: 66 },
        { name: 'Payment Processor', index: 67 },
        { name: 'Treasury Operations Analyst', index: 68 },
        { name: 'Loan Operations Specialist', index: 69 },
        { name: 'Financial Technology (FinTech)', index: 70 },
        { name: 'FinTech Specialist', index: 71 },
        { name: 'Payment System Developer', index: 72 },
        { name: 'Blockchain Developer', index: 73 },
        { name: 'Cryptocurrency Analyst', index: 74 },
        { name: 'Mobile Payment Specialist', index: 75 },
        { name: 'Derivatives', index: 76 },
        { name: 'Derivatives Trader', index: 77 },
        { name: 'Derivatives Analyst', index: 78 },
        { name: 'Futures Trader', index: 79 },
        { name: 'Options Trader', index: 80 },
        { name: 'Derivatives Sales', index: 81 },
        { name: 'Wealth Management', index: 82 },
        { name: 'Wealth Advisor', index: 83 },
        { name: 'Relationship Manager', index: 84 },
        { name: 'Wealth Management Associate', index: 85 },
        { name: 'Trust Advisor', index: 86 },
        { name: 'Family Office Advisor', index: 87 },
        { name: 'Commodities', index: 88 },
        { name: 'Commodity Trader', index: 89 },
        { name: 'Commodity Broker', index: 90 },
        { name: 'Commodities Analyst', index: 91 },
        { name: 'Commodity Sales', index: 92 },
        { name: 'Commodity Risk Manager', index: 93 },
        { name: 'Alternative Investments', index: 94 },
        { name: 'Venture Capitalist', index: 95 },
        { name: 'Private Equity Associate', index: 96 },
        { name: 'Angel Investor', index: 97 },
        { name: 'Alternative Investment Analyst', index: 98 },
        { name: 'Infrastructure Investment Specialist', index: 99 },
        { name: 'Capital Markets', index: 100 },
        { name: 'Equity Analyst', index: 101 },
        { name: 'Fixed Income Analyst', index: 102 },
        { name: 'Capital Markets Analyst', index: 103 },
        { name: 'Securities Sales', index: 104 },
        { name: 'Investment Banker', index: 105 },
        { name: 'Financial Education', index: 106 },
        { name: 'Finance Professor', index: 107 },
        { name: 'Financial Education Instructor', index: 108 },
        { name: 'Finance Author', index: 109 },
        { name: 'Finance Coach', index: 110 },
        { name: 'Financial Literacy Trainer', index: 111 },
      ]
    },
    {
      name: 'Healthcare and Medical',
      index: 8,
      subcategories: [
        { name: 'Nursing', index: 0 },
        { name: 'Registered Nurse', index: 1 },
        { name: 'Nurse Practitioner', index: 2 },
        { name: 'Licensed Practical Nurse', index: 3 },
        { name: 'Certified Nursing Assistant', index: 4 },
        { name: 'Director of Nursing', index: 5 },
        { name: 'Medicine', index: 6 },
        { name: 'Physician', index: 7 },
        { name: 'Surgeon', index: 8 },
        { name: 'Anesthesiologist', index: 9 },
        { name: 'Cardiologist', index: 10 },
        { name: 'Psychiatrist', index: 11 },
        { name: 'Pharmacy', index: 12 },
        { name: 'Pharmacist', index: 13 },
        { name: 'Pharmacy Technician', index: 14 },
        { name: 'Clinical Pharmacist', index: 15 },
        { name: 'Compounding Pharmacist', index: 16 },
        { name: 'Pharmacy Manager', index: 17 },
        { name: 'Medical Imaging', index: 18 },
        { name: 'Radiologic Technologist', index: 19 },
        { name: 'MRI Technologist', index: 20 },
        { name: 'Ultrasound Technologist', index: 21 },
        { name: 'Nuclear Medicine Technologist', index: 22 },
        { name: 'Radiologist', index: 23 },
        { name: 'Medical Laboratory Science', index: 24 },
        { name: 'Medical Technologist', index: 25 },
        { name: 'Medical Laboratory Technician', index: 26 },
        { name: 'Blood Bank Technologist', index: 27 },
        { name: 'Histotechnologist', index: 28 },
        { name: 'Clinical Laboratory Scientist', index: 29 },
        { name: 'Physical Therapy', index: 30 },
        { name: 'Physical Therapist', index: 31 },
        { name: 'Physical Therapy Assistant', index: 32 },
        { name: 'Rehabilitation Specialist', index: 33 },
        { name: 'Orthopedic Specialist', index: 34 },
        { name: 'Neurological Specialist', index: 35 },
        { name: 'Occupational Therapy', index: 36 },
        { name: 'Occupational Therapist', index: 37 },
        { name: 'Occupational Therapy Assistant', index: 38 },
        { name: 'Rehabilitation Specialist', index: 39 },
        { name: 'Pediatric Specialist', index: 40 },
        { name: 'Geriatric Specialist', index: 41 },
        { name: 'Speech Therapy', index: 42 },
        { name: 'Speech-Language Pathologist', index: 43 },
        { name: 'Speech Therapy Assistant', index: 44 },
        { name: 'Voice Specialist', index: 45 },
        { name: 'Fluency Specialist', index: 46 },
        { name: 'Swallowing Specialist', index: 47 },
        { name: 'Behavioral Health', index: 48 },
        { name: 'Psychologist', index: 49 },
        { name: 'Counselor', index: 50 },
        { name: 'Social Worker', index: 51 },
        { name: 'Addiction Specialist', index: 52 },
        { name: 'Marriage and Family Therapist', index: 53 },
        { name: 'Nutrition and Dietetics', index: 54 },
        { name: 'Registered Dietitian', index: 55 },
        { name: 'Nutritionist', index: 56 },
        { name: 'Clinical Dietitian', index: 57 },
        { name: 'Sports Dietitian', index: 58 },
        { name: 'Certified Diabetes Educator', index: 59 },
        { name: 'Health Administration', index: 60 },
        { name: 'Healthcare Administrator', index: 61 },
        { name: 'Hospital CEO', index: 62 },
        { name: 'Practice Manager', index: 63 },
        { name: 'Health Information Manager', index: 64 },
        { name: 'Medical Records Clerk', index: 65 },
        { name: 'Health Education', index: 66 },
        { name: 'Health Educator', index: 67 },
        { name: 'Patient Educator', index: 68 },
        { name: 'Health Promotion Specialist', index: 69 },
        { name: 'Public Health Educator', index: 70 },
        { name: 'Health Coach', index: 71 },
        { name: 'Health Informatics', index: 72 },
        { name: 'Health Informatics Specialist', index: 73 },
        { name: 'Health Information Technician', index: 74 },
        { name: 'Health Data Analyst', index: 75 },
        { name: 'Health Information Manager', index: 76 },
        { name: 'Clinical Informatics Analyst', index: 77 },
        { name: 'Medical Billing and Coding', index: 78 },
        { name: 'Medical Coder', index: 79 },
        { name: 'Medical Biller', index: 80 },
        { name: 'Medical Records Clerk', index: 81 },
        { name: 'Insurance Specialist', index: 82 },
        { name: 'Revenue Cycle Manager', index: 83 },
        { name: 'Healthcare Compliance', index: 84 },
        { name: 'Compliance Officer', index: 85 },
        { name: 'Quality Assurance Specialist', index: 86 },
        { name: 'Risk Management Specialist', index: 87 },
        { name: 'HIPAA Officer', index: 88 },
        { name: 'Medical Auditor', index: 89 },
        { name: 'Hospice and Palliative Care', index: 90 },
        { name: 'Hospice Nurse', index: 91 },
        { name: 'Palliative Care Physician', index: 92 },
        { name: 'Hospice Aide', index: 93 },
        { name: 'Bereavement Counselor', index: 94 },
        { name: 'Volunteer Coordinator', index: 95 },
        { name: 'Home Health', index: 96 },
        { name: 'Home Health Aide', index: 97 },
        { name: 'Home Health Nurse', index: 98 },
        { name: 'Physical Therapist', index: 99 },
        { name: 'Occupational Therapist', index: 100 },
        { name: 'Speech Therapist', index: 101 },
        { name: 'Long-Term Care', index: 102 },
        { name: 'Nursing Home Administrator', index: 103 },
        { name: 'Nursing Home Nurse', index: 104 },
        { name: 'Activity Coordinator', index: 105 },
        { name: 'Certified Nursing Assistant', index: 106 },
        { name: 'Physical Therapist', index: 107 },
        { name: 'Emergency Services', index: 108 },
        { name: 'Emergency Physician', index: 109 },
        { name: 'Emergency Nurse', index: 110 },
        { name: 'Paramedic', index: 111 },
        { name: 'EMT', index: 112 },
        { name: 'Emergency Services Manager', index: 113 },
        { name: 'Telemedicine', index: 114 },
        { name: 'Telehealth Nurse', index: 115 },
        { name: 'Telemedicine Physician', index: 116 },
        { name: 'Telehealth Coordinator', index: 117 },
        { name: 'Telemedicine Technician', index: 118 },
        { name: 'Virtual Health Coach', index: 119 },
      ]
    },
    {
      name: 'Hospitality and Tourism',
      index: 9,
      subcategories: [
        { name: 'Accommodation', index: 0 },
        { name: 'Hotel Manager', index: 1 },
        { name: 'Front Desk Agent', index: 2 },
        { name: 'Housekeeper', index: 3 },
        { name: 'Concierge', index: 4 },
        { name: 'Reservationist', index: 5 },
        { name: 'Food and Beverage Services', index: 6 },
        { name: 'Restaurant Manager', index: 7 },
        { name: 'Chef', index: 8 },
        { name: 'Bartender', index: 9 },
        { name: 'Server', index: 10 },
        { name: 'Sommelier', index: 11 },
        { name: 'Travel and Tourism', index: 12 },
        { name: 'Tour Guide', index: 13 },
        { name: 'Travel Agent', index: 14 },
        { name: 'Cruise Director', index: 15 },
        { name: 'Adventure Guide', index: 16 },
        { name: 'Tourist Information Officer', index: 17 },
        { name: 'Event Planning and Management', index: 18 },
        { name: 'Event Planner', index: 19 },
        { name: 'Conference Coordinator', index: 20 },
        { name: 'Wedding Planner', index: 21 },
        { name: 'Convention Services Manager', index: 22 },
        { name: 'Special Events Manager', index: 23 },
        { name: 'Entertainment', index: 24 },
        { name: 'Casino Dealer', index: 25 },
        { name: 'Theme Park Attendant', index: 26 },
        { name: 'Cruise Ship Entertainer', index: 27 },
        { name: 'DJ', index: 28 },
        { name: 'Entertainer', index: 29 },
        { name: 'Spa and Wellness', index: 30 },
        { name: 'Spa Manager', index: 31 },
        { name: 'Massage Therapist', index: 32 },
        { name: 'Aesthetician', index: 33 },
        { name: 'Yoga Instructor', index: 34 },
        { name: 'Personal Trainer', index: 35 },
        { name: 'Sports and Recreation', index: 36 },
        { name: 'Recreation Director', index: 37 },
        { name: 'Golf Course Manager', index: 38 },
        { name: 'Ski Instructor', index: 39 },
        { name: 'Sports Coach', index: 40 },
        { name: 'Fitness Instructor', index: 41 },
        { name: 'Transportation', index: 42 },
        { name: 'Flight Attendant', index: 43 },
        { name: 'Pilot', index: 44 },
        { name: 'Tour Bus Driver', index: 45 },
        { name: 'Transportation Coordinator', index: 46 },
        { name: 'Car Rental Agent', index: 47 },
        { name: 'Hospitality Education', index: 48 },
        { name: 'Hospitality Professor', index: 49 },
        { name: 'Hospitality Instructor', index: 50 },
        { name: 'Hospitality Trainer', index: 51 },
        { name: 'Curriculum Developer', index: 52 },
        { name: 'Hospitality Program Director', index: 53 },
        { name: 'Destination Marketing and Promotion', index: 54 },
        { name: 'Marketing Director', index: 55 },
        { name: 'Public Relations Manager', index: 56 },
        { name: 'Destination Marketing Manager', index: 57 },
        { name: 'Social Media Manager', index: 58 },
        { name: 'Advertising Manager', index: 59 },
        { name: 'Resort and Timeshare Management', index: 60 },
        { name: 'Resort Manager', index: 61 },
        { name: 'Timeshare Sales Manager', index: 62 },
        { name: 'Vacation Ownership Specialist', index: 63 },
        { name: 'Resort Activities Coordinator', index: 64 },
        { name: 'Resort Sales Executive', index: 65 },
        { name: 'Culinary Tourism', index: 66 },
        { name: 'Culinary Tour Guide', index: 67 },
        { name: 'Food and Wine Tour Guide', index: 68 },
        { name: 'Culinary Event Coordinator', index: 69 },
        { name: 'Food Blogger', index: 70 },
        { name: 'Food Critic', index: 71 },
        { name: 'Hospitality Technology', index: 72 },
        { name: 'Hospitality IT Director', index: 73 },
        { name: 'Hospitality Software Developer', index: 74 },
        { name: 'Hospitality Data Analyst', index: 75 },
        { name: 'Information Security Manager', index: 76 },
        { name: 'E-commerce Manager', index: 77 },
        { name: 'Sustainable Tourism', index: 78 },
        { name: 'Sustainable Tourism Manager', index: 79 },
        { name: 'Ecotourism Guide', index: 80 },
        { name: 'Sustainability Consultant', index: 81 },
        { name: 'Wildlife Conservationist', index: 82 },
        { name: 'Sustainable Development Specialist', index: 83 },
        { name: 'Guest Services', index: 84 },
        { name: 'Guest Service Agent', index: 85 },
        { name: 'Guest Relations Manager', index: 86 },
        { name: 'Bellman', index: 87 },
        { name: 'Doorman', index: 88 },
        { name: 'Room Service Attendant', index: 89 },
        { name: 'Travel Journalism', index: 90 },
        { name: 'Travel Writer', index: 91 },
        { name: 'Travel Photographer', index: 92 },
        { name: 'Travel Editor', index: 93 },
        { name: 'Travel Blogger', index: 94 },
        { name: 'Travel Videographer', index: 95 },
        { name: 'Lodging Real Estate and Development', index: 96 },
        { name: 'Real Estate Developer', index: 97 },
        { name: 'Property Manager', index: 98 },
        { name: 'Construction Manager', index: 99 },
        { name: 'Hotel Asset Manager', index: 100 },
        { name: 'Real Estate Broker', index: 101 },
        { name: 'Hospitality Accounting and Finance', index: 102 },
        { name: 'Director of Finance', index: 103 },
        { name: 'Accounting Manager', index: 104 },
        { name: 'Financial Analyst', index: 105 },
        { name: 'Revenue Manager', index: 106 },
        { name: 'Accounts Payable Specialist', index: 107 },
        { name: 'Hotel Security and Safety', index: 108 },
        { name: 'Security Director', index: 109 },
        { name: 'Safety Manager', index: 110 },
        { name: 'Loss Prevention Specialist', index: 111 },
        { name: 'Risk Management Specialist', index: 112 },
        { name: 'Emergency Preparedness Coordinator', index: 113 },
        { name: 'Hospitality and Tourism Consulting', index: 114 },
        { name: 'Hospitality Consultant', index: 115 },
        { name: 'Tourism Consultant', index: 116 },
        { name: 'Management Consultant', index: 117 },
        { name: 'Business Development Consultant', index: 118 },
        { name: 'Market Research Analyst', index: 119 },
      ]
    },
    {
      name: 'Human Resources and Recruiting',
      index: 10,
      subcategories: [
        { name: 'Recruitment and Selection', index: 0 },
        { name: 'Talent Acquisition Manager', index: 1 },
        { name: 'Recruiter', index: 2 },
        { name: 'HR Generalist', index: 3 },
        { name: 'Employment Specialist', index: 4 },
        { name: 'Interviewer', index: 5 },
        { name: 'Compensation and Benefits', index: 6 },
        { name: 'Compensation Analyst', index: 7 },
        { name: 'Benefits Manager', index: 8 },
        { name: 'Payroll Analyst', index: 9 },
        { name: 'HRIS Analyst', index: 10 },
        { name: 'Total Rewards Manager', index: 11 },
        { name: 'Training and Development', index: 12 },
        { name: 'Learning and Development Specialist', index: 13 },
        { name: 'Training Manager', index: 14 },
        { name: 'Organizational Development Consultant', index: 15 },
        { name: 'Leadership Development Manager', index: 16 },
        { name: 'Talent Management Consultant', index: 17 },
        { name: 'Employee Relations', index: 18 },
        { name: 'Employee Relations Specialist', index: 19 },
        { name: 'HR Business Partner', index: 20 },
        { name: 'Labor Relations Manager', index: 21 },
        { name: 'Workplace Investigator', index: 22 },
        { name: 'Ombudsperson', index: 23 },
        { name: 'Performance Management', index: 24 },
        { name: 'Performance Management Specialist', index: 25 },
        { name: 'Performance Improvement Manager', index: 26 },
        { name: 'Employee Engagement Manager', index: 27 },
        { name: 'Performance Coach', index: 28 },
        { name: 'Succession Planning Specialist', index: 29 },
        { name: 'Diversity and Inclusion', index: 30 },
        { name: 'Diversity and Inclusion Manager', index: 31 },
        { name: 'EEO Compliance Specialist', index: 32 },
        { name: 'Multicultural Affairs Officer', index: 33 },
        { name: 'Diversity Recruiter', index: 34 },
        { name: 'Affirmative Action Specialist', index: 35 },
        { name: 'HR Information Systems', index: 36 },
        { name: 'HRIS Analyst', index: 37 },
        { name: 'HR Systems Manager', index: 38 },
        { name: 'HR Data Analyst', index: 39 },
        { name: 'HR Technology Specialist', index: 40 },
        { name: 'HR Database Administrator', index: 41 },
        { name: 'Compliance and Ethics', index: 42 },
        { name: 'HR Compliance Manager', index: 43 },
        { name: 'Ethics and Compliance Specialist', index: 44 },
        { name: 'HR Legal Counsel', index: 45 },
        { name: 'Employment Law Specialist', index: 46 },
        { name: 'Workers\' Compensation Specialist', index: 47 },
        { name: 'HR Operations', index: 48 },
        { name: 'HR Operations Manager', index: 49 },
        { name: 'HR Coordinator', index: 50 },
        { name: 'HR Assistant', index: 51 },
        { name: 'Onboarding Specialist', index: 52 },
        { name: 'Offboarding Specialist', index: 53 },
        { name: 'Benefits Administration', index: 54 },
        { name: 'Benefits Administrator', index: 55 },
        { name: 'Retirement Plan Specialist', index: 56 },
        { name: 'Health and Welfare Specialist', index: 57 },
        { name: 'Leaves of Absence Administrator', index: 58 },
        { name: 'COBRA Specialist', index: 59 },
      ]
    },
    {
      name: 'Information Technology',
      index: 11,
      subcategories: [
        { name: 'Software Development', index: 0 },
        { name: 'Front-End Developer', index: 1 },
        { name: 'Back-End Developer', index: 2 },
        { name: 'Full-Stack Developer', index: 3 },
        { name: 'Mobile Developer', index: 4 },
        { name: 'Game Developer', index: 5 },
        { name: 'Database Management', index: 6 },
        { name: 'Database Administrator', index: 7 },
        { name: 'Data Analyst', index: 8 },
        { name: 'Database Developer', index: 9 },
        { name: 'Data Warehouse Architect', index: 10 },
        { name: 'Business Intelligence Analyst', index: 11 },
        { name: 'Network and Systems Administration', index: 12 },
        { name: 'Network Engineer', index: 13 },
        { name: 'Systems Administrator', index: 14 },
        { name: 'IT Support Technician', index: 15 },
        { name: 'Cloud Architect', index: 16 },
        { name: 'DevOps Engineer', index: 17 },
        { name: 'Cybersecurity', index: 18 },
        { name: 'Information Security Analyst', index: 19 },
        { name: 'Security Engineer', index: 20 },
        { name: 'Penetration Tester', index: 21 },
        { name: 'Security Consultant', index: 22 },
        { name: 'Incident Responder', index: 23 },
        { name: 'Project Management', index: 24 },
        { name: 'IT Project Manager', index: 25 },
        { name: 'Agile Project Manager', index: 26 },
        { name: 'Scrum Master', index: 27 },
        { name: 'Business Analyst', index: 28 },
        { name: 'Product Manager', index: 29 },
        { name: 'Web Development', index: 30 },
        { name: 'Web Designer', index: 31 },
        { name: 'Web Developer', index: 32 },
        { name: 'UI/UX Designer', index: 33 },
        { name: 'Front-End Developer', index: 34 },
        { name: 'Back-End Developer', index: 35 },
        { name: 'Artificial Intelligence and Machine Learning', index: 36 },
        { name: 'Data Scientist', index: 37 },
        { name: 'Machine Learning Engineer', index: 38 },
        { name: 'AI Research Scientist', index: 39 },
        { name: 'Natural Language Processing (NLP) Engineer', index: 40 },
        { name: 'Computer Vision Engineer', index: 41 },
        { name: 'Quality Assurance and Testing', index: 42 },
        { name: 'Quality Assurance Engineer', index: 43 },
        { name: 'Test Automation Engineer', index: 44 },
        { name: 'Performance Engineer', index: 45 },
        { name: 'User Acceptance Tester', index: 46 },
        { name: 'Software Tester', index: 47 },
        { name: 'Cloud Computing', index: 48 },
        { name: 'Cloud Engineer', index: 49 },
        { name: 'Cloud Administrator', index: 50 },
        { name: 'Cloud Architect', index: 51 },
        { name: 'Cloud Consultant', index: 52 },
        { name: 'Cloud Security Engineer', index: 53 },
        { name: 'Enterprise Systems', index: 54 },
        { name: 'ERP Specialist', index: 55 },
        { name: 'CRM Specialist', index: 56 },
        { name: 'Business Process Analyst', index: 57 },
        { name: 'Supply Chain Analyst', index: 58 },
        { name: 'Enterprise Architect', index: 59 },
        { name: 'Data Science and Analytics', index: 60 },
        { name: 'Data Scientist', index: 61 },
        { name: 'Business Analyst', index: 62 },
        { name: 'Data Analyst', index: 63 },
        { name: 'Data Engineer', index: 64 },
        { name: 'Big Data Engineer', index: 65 },
        { name: 'Web Analytics', index: 66 },
        { name: 'Web Analyst', index: 67 },
        { name: 'Digital Marketing Analyst', index: 68 },
        { name: 'Web Optimization Analyst', index: 69 },
        { name: 'E-Commerce Analyst', index: 70 },
        { name: 'A/B Testing Analyst', index: 71 },
        { name: 'User Experience and Interface Design', index: 72 },
        { name: 'UX Designer', index: 73 },
        { name: 'UI Designer', index: 74 },
        { name: 'Information Architect', index: 75 },
        { name: 'Interaction Designer', index: 76 },
        { name: 'Visual Designer', index: 77 },
        { name: 'Mobile Application Development', index: 78 },
        { name: 'iOS Developer', index: 79 },
        { name: 'Android Developer', index: 80 },
        { name: 'React Native Developer', index: 81 },
        { name: 'Xamarin Developer', index: 82 },
        { name: 'Mobile QA Engineer', index: 83 },
        { name: 'IT Consulting', index: 84 },
        { name: 'IT Consultant', index: 85 },
        { name: 'Business Analyst', index: 86 },
        { name: 'Systems Analyst', index: 87 },
        { name: 'IT Auditor', index: 88 },
        { name: 'IT Strategy Consultant', index: 89 },
        { name: 'Technical Writing and Documentation', index: 90 },
        { name: 'Technical Writer', index: 91 },
        { name: 'Technical Editor', index: 92 },
        { name: 'Technical Illustrator', index: 93 },
        { name: 'Knowledge Management Specialist', index: 94 },
        { name: 'Technical Trainer', index: 95 },
      ]
    },
    {
      name: 'Legal and Law Enforcement',
      index: 12,
      subcategories: [
        { name: 'Corporate Law', index: 0 },
        { name: 'Corporate Attorney', index: 1 },
        { name: 'Mergers and Acquisitions Attorney', index: 2 },
        { name: 'Securities Attorney', index: 3 },
        { name: 'Business Law Attorney', index: 4 },
        { name: 'Intellectual Property Attorney', index: 5 },
        { name: 'Litigation', index: 6 },
        { name: 'Litigation Attorney', index: 7 },
        { name: 'Trial Attorney', index: 8 },
        { name: 'Appellate Attorney', index: 9 },
        { name: 'Criminal Defense Attorney', index: 10 },
        { name: 'Plaintiff Attorney', index: 11 },
        { name: 'Real Estate Law', index: 12 },
        { name: 'Real Estate Attorney', index: 13 },
        { name: 'Property Law Attorney', index: 14 },
        { name: 'Land Use Attorney', index: 15 },
        { name: 'Environmental Attorney', index: 16 },
        { name: 'Construction Law Attorney', index: 17 },
        { name: 'Intellectual Property Law', index: 18 },
        { name: 'Patent Attorney', index: 19 },
        { name: 'Trademark Attorney', index: 20 },
        { name: 'Copyright Attorney', index: 21 },
        { name: 'Licensing Attorney', index: 22 },
        { name: 'IP Litigator', index: 23 },
        { name: 'Employment Law', index: 24 },
        { name: 'Employment Attorney', index: 25 },
        { name: 'Labor Law Attorney', index: 26 },
        { name: 'Human Resources Attorney', index: 27 },
        { name: 'Workplace Discrimination Attorney', index: 28 },
        { name: 'Employee Benefits Attorney', index: 29 },
        { name: 'Immigration Law', index: 30 },
        { name: 'Immigration Attorney', index: 31 },
        { name: 'Business Immigration Attorney', index: 32 },
        { name: 'Family Immigration Attorney', index: 33 },
        { name: 'Asylum Attorney', index: 34 },
        { name: 'Deportation Defense Attorney', index: 35 },
        { name: 'Family Law', index: 36 },
        { name: 'Family Law Attorney', index: 37 },
        { name: 'Divorce Attorney', index: 38 },
        { name: 'Child Custody Attorney', index: 39 },
        { name: 'Adoption Attorney', index: 40 },
        { name: 'Domestic Violence Attorney', index: 41 },
        { name: 'Bankruptcy Law', index: 42 },
        { name: 'Bankruptcy Attorney', index: 43 },
        { name: 'Debt Relief Attorney', index: 44 },
        { name: 'Creditors\' Rights Attorney', index: 45 },
        { name: 'Foreclosure Defense Attorney', index: 46 },
        { name: 'Financial Restructuring Attorney', index: 47 },
        { name: 'Criminal Law', index: 48 },
        { name: 'Criminal Defense Attorney', index: 49 },
        { name: 'Prosecuting Attorney', index: 50 },
        { name: 'White Collar Crime Attorney', index: 51 },
        { name: 'DUI/DWI Attorney', index: 52 },
        { name: 'Cybercrime Attorney', index: 53 },
        { name: 'Tax Law', index: 54 },
        { name: 'Tax Attorney', index: 55 },
        { name: 'Estate Planning Attorney', index: 56 },
        { name: 'Business Tax Attorney', index: 57 },
        { name: 'International Tax Attorney', index: 58 },
        { name: 'IRS Litigation Attorney', index: 59 },
        { name: 'Environmental Law', index: 60 },
        { name: 'Environmental Attorney', index: 61 },
        { name: 'Natural Resources Attorney', index: 62 },
        { name: 'Clean Energy Attorney', index: 63 },
        { name: 'Sustainability Attorney', index: 64 },
        { name: 'Climate Change Attorney', index: 65 },
        { name: 'Health Law', index: 66 },
        { name: 'Health Care Attorney', index: 67 },
        { name: 'Medical Malpractice Attorney', index: 68 },
        { name: 'FDA Attorney', index: 69 },
        { name: 'Hospital Attorney', index: 70 },
        { name: 'Pharmaceutical Attorney', index: 71 },
        { name: 'Education Law', index: 72 },
        { name: 'Education Attorney', index: 73 },
        { name: 'Student Rights Attorney', index: 74 },
        { name: 'Special Education Attorney', index: 75 },
        { name: 'Title IX Attorney', index: 76 },
        { name: 'Faculty and Staff Attorney', index: 77 },
        { name: 'Sports Law', index: 78 },
        { name: 'Sports Attorney', index: 79 },
        { name: 'Athlete Advocate', index: 80 },
        { name: 'Team Counsel', index: 81 },
        { name: 'League Counsel', index: 82 },
        { name: 'International Law', index: 83 },
        { name: 'International Business Attorney', index: 84 },
        { name: 'International Trade Attorney', index: 85 },
        { name: 'Human Rights Attorney', index: 86 },
        { name: 'Foreign Investment Attorney', index: 87 },
        { name: 'International Arbitration Attorney', index: 88 },
        { name: 'Government Law', index: 89 },
        { name: 'Government Attorney', index: 90 },
        { name: 'Administrative Law Judge', index: 91 },
        { name: 'Legislative Counsel', index: 92 },
        { name: 'Lobbyist', index: 93 },
        { name: 'Public Defender', index: 94 },
        { name: 'Entertainment Law', index: 95 },
        { name: 'Entertainment Attorney', index: 96 },
        { name: 'Music Attorney', index: 97 },
        { name: 'Film and Television Attorney', index: 98 },
        { name: 'Sports and Athlete Attorney', index: 99 },
        { name: 'Intellectual Property Attorney', index: 100 },
        { name: 'Maritime Law', index: 101 },
        { name: 'Admiralty Attorney', index: 102 },
        { name: 'Maritime Litigator', index: 103 },
        { name: 'Shipping Attorney', index: 104 },
        { name: 'Offshore Oil and Gas Attorney', index: 105 },
        { name: 'Marine Insurance Attorney', index: 106 },
        { name: 'Aviation Law', index: 107 },
        { name: 'Aviation Attorney', index: 108 },
        { name: 'Airline Attorney', index: 109 },
        { name: 'FAA Attorney', index: 110 },
        { name: 'Aircraft Manufacturer Attorney', index: 111 },
        { name: 'Airport Attorney', index: 112 },
        { name: 'Construction Law', index: 113 },
        { name: 'Construction Attorney', index: 114 },
        { name: 'Contract Attorney', index: 115 },
        { name: 'Insurance Attorney', index: 116 },
        { name: 'Litigation Attorney', index: 117 },
        { name: 'Construction Defect Attorney', index: 118 },
      ]
    },
    {
      name: 'Manufacturing',
      index: 13,
      subcategories: [
        { name: 'Production', index: 0 },
        { name: 'Production Manager', index: 1 },
        { name: 'Production Supervisor', index: 2 },
        { name: 'Machine Operator', index: 3 },
        { name: 'Quality Control and Assurance', index: 4 },
        { name: 'Quality Control Manager', index: 5 },
        { name: 'Quality Assurance Technician', index: 6 },
        { name: 'Inspection Supervisor', index: 7 },
        { name: 'Maintenance and Repair', index: 8 },
        { name: 'Maintenance Manager', index: 9 },
        { name: 'Maintenance Technician', index: 10 },
        { name: 'Repair Technician', index: 11 },
        { name: 'Supply Chain and Logistics', index: 12 },
        { name: 'Supply Chain Manager', index: 13 },
        { name: 'Logistics Coordinator', index: 14 },
        { name: 'Materials Planner', index: 15 },
        { name: 'Engineering and Design', index: 16 },
        { name: 'Manufacturing Engineer', index: 17 },
        { name: 'Design Engineer', index: 18 },
        { name: 'Industrial Designer', index: 19 },
        { name: 'Health and Safety', index: 20 },
        { name: 'Health and Safety Manager', index: 21 },
        { name: 'Safety Engineer', index: 22 },
        { name: 'Environmental Health and Safety Specialist', index: 23 },
      ]
    },
    {
      name: 'Sales & Marketing',
      index: 14,
      subcategories: [
        { name: 'Brand Management', index: 0 },
        { name: 'Brand Manager', index: 1 },
        { name: 'Marketing Manager', index: 2 },
        { name: 'Product Manager', index: 3 },
        { name: 'Digital Marketing Analyst', index: 4 },
        { name: 'Social Media Manager', index: 5 },
        { name: 'Advertising', index: 6 },
        { name: 'Advertising Executive', index: 7 },
        { name: 'Advertising Manager', index: 8 },
        { name: 'Advertising Sales Representative', index: 9 },
        { name: 'Media Planner', index: 10 },
        { name: 'Creative Director', index: 11 },
        { name: 'Public Relations', index: 12 },
        { name: 'Public Relations Specialist', index: 13 },
        { name: 'Public Relations Manager', index: 14 },
        { name: 'Communications Director', index: 15 },
        { name: 'Press Secretary', index: 16 },
        { name: 'Crisis Manager', index: 17 },
        { name: 'Sales', index: 18 },
        { name: 'Sales Representative', index: 19 },
        { name: 'Sales Manager', index: 20 },
        { name: 'Account Manager', index: 21 },
        { name: 'Business Development Manager', index: 22 },
        { name: 'Inside Sales Representative', index: 23 },
        { name: 'Business-to-Business (B2B) Marketing', index: 24 },
        { name: 'B2B Marketing Manager', index: 25 },
        { name: 'Account Manager', index: 26 },
        { name: 'Customer Success Manager', index: 27 },
        { name: 'Strategic Account Executive', index: 28 },
        { name: 'Market Research Analyst', index: 29 },
        { name: 'Business-to-Consumer (B2C) Marketing', index: 30 },
        { name: 'B2C Marketing Manager', index: 31 },
        { name: 'E-commerce Manager', index: 32 },
        { name: 'Customer Acquisition Manager', index: 33 },
        { name: 'Loyalty Program Manager', index: 34 },
        { name: 'Customer Insights Analyst', index: 35 },
        { name: 'Digital Marketing', index: 36 },
        { name: 'Digital Marketing Manager', index: 37 },
        { name: 'SEO Specialist', index: 38 },
        { name: 'Social Media Manager', index: 39 },
        { name: 'Content Marketing Manager', index: 40 },
        { name: 'Email Marketing Specialist', index: 41 },
        { name: 'Content Marketing', index: 42 },
        { name: 'Content Marketing Manager', index: 43 },
        { name: 'Content Strategist', index: 44 },
        { name: 'Copywriter', index: 45 },
        { name: 'Editorial Manager', index: 46 },
        { name: 'Graphic Designer', index: 47 },
        { name: 'Direct Marketing', index: 48 },
        { name: 'Direct Marketing Manager', index: 49 },
        { name: 'Telemarketer', index: 50 },
        { name: 'Direct Mail Specialist', index: 51 },
        { name: 'Email Marketing Specialist', index: 52 },
        { name: 'Direct Response Copywriter', index: 53 },
        { name: 'Event Marketing', index: 54 },
        { name: 'Event Marketing Manager', index: 55 },
        { name: 'Event Coordinator', index: 56 },
        { name: 'Trade Show Specialist', index: 57 },
        { name: 'Event Planner', index: 58 },
        { name: 'Sponsorship Manager', index: 59 },
        { name: 'International Marketing', index: 60 },
        { name: 'International Marketing Manager', index: 61 },
        { name: 'International Sales Manager', index: 62 },
        { name: 'Export Manager', index: 63 },
        { name: 'Global Marketing Manager', index: 64 },
        { name: 'Localization Specialist', index: 65 },
        { name: 'Market Research', index: 66 },
        { name: 'Market Research Analyst', index: 67 },
        { name: 'Market Research Manager', index: 68 },
        { name: 'Survey Researcher', index: 69 },
        { name: 'Focus Group Moderator', index: 70 },
        { name: 'Channel Marketing', index: 71 },
        { name: 'Channel Marketing Manager', index: 72 },
        { name: 'Channel Sales Manager', index: 73 },
        { name: 'Partner Marketing Specialist', index: 74 },
        { name: 'Distributor Manager', index: 75 },
        { name: 'Retail Marketing Manager', index: 76 },
        { name: 'Retail Marketing', index: 77 },
        { name: 'Retail Marketing Manager', index: 78 },
        { name: 'Merchandising Manager', index: 79 },
        { name: 'Visual Merchandiser', index: 80 },
        { name: 'Trade Marketing Manager', index: 81 },
        { name: 'Category Manager', index: 82 },
        { name: 'Product Marketing', index: 83 },
        { name: 'Product Marketing Manager', index: 84 },
        { name: 'Product Manager', index: 85 },
        { name: 'Product Analyst', index: 86 },
        { name: 'Pricing Manager', index: 87 },
        { name: 'Product Launch Manager', index: 88 },
        { name: 'Field Marketing', index: 89 },
        { name: 'Field Marketing Manager', index: 90 },
        { name: 'Event Coordinator', index: 91 },
        { name: 'Territory Sales Representative', index: 92 },
        { name: 'Product Demonstrator', index: 93 },
        { name: 'Local Marketing Manager', index: 94 },
        { name: 'Account-Based Marketing', index: 95 },
        { name: 'Account-Based Marketing Manager', index: 96 },
        { name: 'Account Executive', index: 97 },
        { name: 'Account Manager', index: 98 },
        { name: 'Lead Generation Specialist', index: 99 },
        { name: 'Sales Development Representative', index: 100 },
        { name: 'Social Media Marketing', index: 101 },
        { name: 'Social Media Manager', index: 102 },
        { name: 'Social Media Strategist', index: 103 },
        { name: 'Community Manager', index: 104 },
        { name: 'Content Creator', index: 105 },
        { name: 'Influencer Marketing Manager', index: 106 },
        { name: 'Search Engine Marketing', index: 107 },
        { name: 'Search Engine Marketing Manager', index: 108 },
        { name: 'Pay-Per-Click Specialist', index: 109 },
        { name: 'Search Engine Optimization Specialist', index: 110 },
        { name: 'Landing Page Designer', index: 111 },
      ]
    },
    {
      name: 'Science & Research',
      index: 15,
      subcategories: [
        { name: 'Biotechnology', index: 0 },
        { name: 'Biochemist', index: 1 },
        { name: 'Biomedical engineer', index: 2 },
        { name: 'Biostatistician', index: 3 },
        { name: 'Chemistry', index: 4 },
        { name: 'Analytical chemist', index: 5 },
        { name: 'Medicinal chemist', index: 6 },
        { name: 'Polymer chemist', index: 7 },
        { name: 'Physics', index: 8 },
        { name: 'Astrophysicist', index: 9 },
        { name: 'Nuclear physicist', index: 10 },
        { name: 'Materials physicist', index: 11 },
        { name: 'Earth and Environmental Science', index: 12 },
        { name: 'Hydrologist', index: 13 },
        { name: 'Geomorphologist', index: 14 },
        { name: 'Atmospheric scientist', index: 15 },
        { name: 'Microbiology', index: 16 },
        { name: 'Microbiologist', index: 17 },
        { name: 'Mycologist', index: 18 },
        { name: 'Immunologist', index: 19 },
        { name: 'Psychology and Neuroscience', index: 20 },
        { name: 'Cognitive psychologist', index: 21 },
        { name: 'Neuroscientist', index: 22 },
        { name: 'Behavioral geneticist', index: 23 },
        { name: 'Genetics and Genomics', index: 24 },
        { name: 'Genetic counselor', index: 25 },
        { name: 'Geneticist', index: 26 },
        { name: 'Genomic scientist', index: 27 },
        { name: 'Ecology and Evolution', index: 28 },
        { name: 'Ecologist', index: 29 },
        { name: 'Evolutionary biologist', index: 30 },
        { name: 'Conservation biologist', index: 31 },
        { name: 'Mathematics', index: 32 },
        { name: 'Statistician', index: 33 },
        { name: 'Actuary', index: 34 },
        { name: 'Operations research analyst', index: 35 },
        { name: 'Computer Science', index: 36 },
        { name: 'Artificial intelligence researcher', index: 37 },
        { name: 'Computer network architect', index: 38 },
        { name: 'Cybersecurity analyst', index: 39 },
        { name: 'Science Education', index: 40 },
        { name: 'Science teacher', index: 41 },
        { name: 'Curriculum developer', index: 42 },
        { name: 'Science education specialist', index: 43 },
        { name: 'Marine Science', index: 44 },
        { name: 'Oceanographer', index: 45 },
        { name: 'Marine biologist', index: 46 },
        { name: 'Aquatic ecologist', index: 47 },
        { name: 'Astronomy', index: 48 },
        { name: 'Astronomer', index: 49 },
        { name: 'Astrophysicist', index: 50 },
        { name: 'Astrobiologist', index: 51 },
        { name: 'Food Science', index: 52 },
        { name: 'Food chemist', index: 53 },
        { name: 'Flavor chemist', index: 54 },
        { name: 'Sensory analyst', index: 55 },
        { name: 'Materials Science', index: 56 },
        { name: 'Metallurgist', index: 57 },
        { name: 'Materials engineer', index: 58 },
        { name: 'Composite materials scientist', index: 59 },
        { name: 'Biomedical Science', index: 60 },
        { name: 'Biomedical engineer', index: 61 },
        { name: 'Medical laboratory technician', index: 62 },
        { name: 'Biomedical research scientist', index: 63 },
        { name: 'Immunology', index: 64 },
        { name: 'Immunologist', index: 65 },
        { name: 'Medical research scientist', index: 66 },
        { name: 'Pathologist', index: 67 },
        { name: 'Biophysics', index: 68 },
        { name: 'Biophysicist', index: 69 },
        { name: 'Biomedical engineer', index: 70 },
        { name: 'Medical physicist', index: 71 },
        { name: 'Social Science Research', index: 72 },
        { name: 'Survey researcher', index: 73 },
        { name: 'Social science research analyst', index: 74 },
        { name: 'Public opinion researcher', index: 75 },
        { name: 'Scientific Publications and Communications', index: 76 },
        { name: 'Science writer', index: 77 },
        { name: 'Science editor', index: 78 },
        { name: 'Science journalist', index: 79 },
      ]
    },
  ];
  
  module.exports = jobCategories;
  